spring:
  profiles:
    active: "main"
  data:
    mongodb:
      uri: ${DEPOSIT_QUERY_RESULTS_DATASOURCE_URL:mongodb://test:test@192.168.3.27:27017/deposit_query_api_db}

server:
  port: 8082

kafka:
  bootstrapAddress:  ${KAFKA_ADDRESS:localhost:9092}
  consumer:
    auto-offset-reset: earliest

message:
  topic:
    created-deposits:
      name: ${DEPOSIT_CREATED_DEPOSITS_TOPIC_NAME:createdDeposits}
    changed-deposits:
      name: ${DEPOSIT_CHANGED_DEPOSITS_TOPIC_NAME:changedDeposits}
    removed-deposits:
      name: ${DEPOSIT_REMOVED_DEPOSITS_TOPIC_NAME:removedDeposits}